services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8493:8080
    networks:
      - nginx-proxy_net
    env_file: "/env/jekuari-search/.env"

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - nginx-proxy_net

networks:
  nginx-proxy_net:
    external: true

volumes:
  redis_data:
    driver: local
